Add files via upload
paresy/SymconMisc pull request #10
Opened 2018-02-17 12:43 UTC by demel42

gezielte Abfrage einer bestimmten Wetterstation via PWS-ID

2018-03-01 05:31 UTC, paresy requested changes
Vielen Dank für den PR. Ich hab noch einen kleinen Wusch, würde ihn dann aber gerne Mergen.

2018-03-01 05:31 UTC, paresy commented on WundergroundWeather/form.json
> +	{ "type": "ValidationTextBox", "name": "PWSID", "caption": "PWS-ID" },
Magst du hier noch ein "Label" hinzugefügen, dass auf den Umstand hinweist, dass die PWS-ID optional ist? Sofern gesetzt jedoch bevorzugt wird?

2018-03-02 17:37 UTC, demel42 commented
Label mit Beschreibung hinzugefügt. Ich hoffe das ist verständlich.

2018-03-20 10:54 UTC, paresy approved these changes

2018-03-20 10:55 UTC, merged