Last Alert hinzugefügt - der letzte Sensor, der ausgelöst hat
paresy/SymconMisc pull request #13
Opened 2018-10-26 16:34 UTC by Schnittcher

Ich habe eine Variable hinzugefügt, in der immer die VariablenID, des letzten Sensors steht, der den Alarm ausgelöst hat.

2018-10-26 18:47 UTC, paresy requested changes
Was hälst du davon statt der ID (die hilft im WebFront ja nicht) die IPS_GetLocation anzuzeigen?

Und hinter den Kommas bitte noch Leerzeichen :)

2018-10-26 18:50 UTC, Schnittcher commented
Ich hatte gedacht, lieber die ID anzeigen, damit später jeder selbst damit machen kann was er will.

Die Leerzeichen im JSON?

2018-10-26 18:53 UTC, Nall-chan commented
Warum ist denn da so häufig SetValue?
Reicht nicht einmal vor oder nach dem Switch?

2018-10-26 18:55 UTC, Schnittcher commented
Weil sonst beim false setzen auch der Wert gesetzt wird, ich bin der Meinung, das sollte nur passieren wenn ein Sensor auf true gesetzt wird.

2018-10-26 18:57 UTC, paresy commented
Es macht auf jeden Fall Sinn nur bei "True" die ID zu speichern.

2018-10-26 18:58 UTC, paresy commented on Alarmierung/README.md
> +Last Alert   | Integer   | Die VariablenID, des letzten Sensors, der ausgelöst hat.
Ich glaube die Kommas hier können dafür weg

2018-10-26 19:00 UTC, Schnittcher commented
Also wie gesagt, wenn du lieber den Klarnamen haben willst, mache ich das noch. Ich dachte so, kann ich wenigstens mehr mit der Variablen ID noch im Nachhinein in Scripten machen.

2018-10-26 19:02 UTC, paresy commented
Prinzipiell hast du Recht. Ich überlege nur, ob wir jemals in Modulen irgendwelche IDs in Variablen getan haben. Zumal die ja im WebFront sichtbar sind und nicht wirklich nützen/helfen. Hast du irgendein Modul im Kopf dass eine ID speichert?

2018-10-26 19:02 UTC, Nall-chan commented
Dann in SetAlert wenn true.
Der Switch ist der Filter und führt eine Funktion aus, da reicht es doch das SetValue einmalig in SetAlert einzubauen ;)

2018-10-26 19:04 UTC, Schnittcher commented
SetAlert ist aber eine Public Funktion, darüber hatte ich auch nachgedacht, dann müsste man an der Stelle auch immer etwas mitgeben, wenn man einen Alarm per Script auslöst.

2018-10-26 19:04 UTC, paresy commented
Da fehlt dir aber Zugriff auf die $SourceID. Man könnte SetAlert ja umbiegen in CallAlert und das dann vorher als anonyme Funktion abbilden z.B. 

$CallAlert = function() use($SourceID) {
 ...
};

2018-10-26 19:06 UTC, Nall-chan commented
Äh, stimmt ja. Ver*** ich sollte keine Diffs und Code mehr am Handy lesen.

2018-10-26 19:08 UTC, Schnittcher commented
Das übersteigt meine derzeitigen PHP Kenntnisse. Wenn du dazu ein Beispiel hast, sehr gerne! :D

Für mich persönlich würde auch der Klarname reichen, da ich Pushnachrichten mit dem Namen versenden will. Oder die Variable einfach auf nicht sichtbar setzen? Wobei das ja wieder gegen die Best Practice sprechen würden, richtig?

2018-10-26 19:12 UTC, Nall-chan commented
Alternative: 
Entweder alle If im Switch im invertieren und dann anstatt SetAlert mit Return abbrechen.
SetValue und SetAlert dann nach dem Switch.
Oder aller SetAlert im Switch ersetzen durch eine lokale Variable.
Und die nach dem Switch abfragen und dann SetValue+SetAlert.

2018-10-26 19:49 UTC, Schnittcher commented
Aber wenn man jetzt invertiert, hat man doch das Problem, wenn jemand etwas angibt was nicht abgefragt wird, dann wird's da immer ein true geben, also wäre das auch nicht so super, oder nicht?

2018-11-08 09:38 UTC, paresy commented
Ich bin hier immer noch unglücklich. Ich habe immer noch kein Modul gefunden, dass eine ObjektID in einer sichtbaren Variable speichert. Niels hatte folgende Idee:
* Die ObjektID vom Auslöser wird in einem Attribut (5.1) gespeichert
* Dieses Attribut kann man über eine public Funktion (z.B. GetLastAlertID) auslesen
* Zusätzlich gibt es in der Visu eine String Variable die "ParentName\ObjektName" anzeigt, damit in der Visu etwas nützliches angezeigt wird.

Was hältst du davon?

2018-11-08 09:47 UTC, Schnittcher commented
Wäre doch genau das, was man will.
Man kommt an die ID und an den Namen im Webfront.

Michael Maroszek <notifications@github.com> schrieb am Do. 8. Nov. 2018 um
10:38:

> Ich bin hier immer noch unglücklich. Ich habe immer noch kein Modul
> gefunden, dass eine ObjektID in einer sichtbaren Variable speichert. Niels
> hatte folgende Idee:
>
>    - Die ObjektID vom Auslöser wird in einem Attribut (5.1) gespeichert
>    - Dieses Attribut kann man über eine public Funktion (z.B.
>    GetLastAlertID) auslesen
>    - Zusätzlich gibt es in der Visu eine String Variable die
>    "ParentName\ObjektName" anzeigt, damit in der Visu etwas nützliches
>    angezeigt wird.
>
> Was hältst du davon?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/symcon/SymconMisc/pull/13#issuecomment-436932325>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ADJrif1TIB5pVPb55ns2BzWSwvYIZm-Qks5us_uIgaJpZM4X8kym>
> .
>

2019-08-16 09:23 UTC, paresy commented
Da es ja die Attribute mittlerweile gibt, könnte man dies einbauen. Falls du daran noch Interesse hast, müsste der neue PR jedoch hier hin gehen: https://github.com/symcon/Alarmierung

2019-08-16 09:23 UTC, closed without merging